App\Entity\Usuari:
    attributes:
        id:
            groups: ['usuari']
        email:
            groups: ['usuari']
        roles:
             groups: ['usuari']
        ban:
             groups: ['usuari']
        # avatar:
        #     groups: ['usuari']

